### ISSUE TITLE
Broken link for   An Overview of Statistical Learning Theory with examplesLinks to an external site.

### ISSUE THREAD

**Issue by kjspring** [learn-co-curriculum/dsc-stat-learning-theory#2]
## Link to Canvas

https://learning.flatironschool.com/courses/5316/pages/statistical-learning-theory?module_item_id=408406

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ x] Other (explain below)

### Source

```
Not Found

The requested URL /~harman/Papers/SLT-tutorial.pdf was not found on this server.

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by hoffm386** [comment]
Resolved by https://github.com/learn-co-curriculum/dsc-stat-learning-theory/commit/0e8bc60ccd55407b868dd04906619726426cc27e

The new tutorial link is https://www.princeton.edu/~kulkarni/Papers/Journals/j077_2011_KulHar_WileyTutorial.pdf
